# Generated by Django 4.2 on 2023-05-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airlineID', models.AutoField(primary_key=True, serialize=False)),
                ('airline_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flightID', models.AutoField(primary_key=True, serialize=False)),
                ('tripType', models.CharField(default='', max_length=255)),
                ('countryFrom', models.CharField(max_length=255)),
                ('countryTo', models.CharField(max_length=255)),
                ('departDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('airlineID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.airline')),
            ],
        ),
    ]
