# Generated by Django 4.2 on 2023-05-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='airlineID',
        ),
    ]
