# Generated by Django 4.2 on 2023-05-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airlineID', models.AutoField(primary_key=True, serialize=False)),
                ('airline_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightID', models.AutoField(primary_key=True, serialize=False)),
                ('flightDestination', models.CharField(max_length=255)),
                ('flightTime', models.TimeField()),
                ('flightDate', models.DateField()),
                ('flightPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('airlineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.airline')),
            ],
        ),
    ]
